apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: dito-api
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: dito-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dito-api-database
  namespace: dito-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: dito-api-database
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dito-api-staging/api/database
