apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dito-api-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dito/desafio-devops-dito.git
    targetRevision: main
    path: manifests/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: dito-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
